### ISSUE TITLE
Switching to the Network-of-Terms interface causes loss of unsaved edits

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#399] opened 2021-08-04 13:56 UTC
If you switch to the Network-of-Terms interface in the process of editing the metadata of an object the previous edits are lost when they are not saved first.

**Comment by sdevalk** [comment] 2021-08-09 10:00
Same as https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/362?

**Comment by lem-onade** [comment] 2021-08-16 08:26
Closing, duplicate of #362

**Closed by lem-onade** 2021-08-16 08:26 UTC
Labels: bug, PRIORITY
