### ISSUE TITLE
Change name 'Collectiebeheersysteem'

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#403] opened 2021-08-06 14:26 UTC
The title of the login page is 'Collectiebeheersysteem'. Can this be changed to 'Collectieregistratiesysteem' (to stay in sync with abbreviation 'Solid CRS')?

![Screenshot 2021-08-06 at 16 23 34](https://user-images.githubusercontent.com/606948/128525336-fc95d1ff-1dfc-4f48-b6a9-e95b866edbca.png)

**Comment by lem-onade** [comment] 2021-08-13 13:08
closing, duplicate of #382

**Closed by lem-onade** 2021-08-13 13:08 UTC
Labels: enhancement
